export const students = [
    { id: 1, nombre: 'Juan', apellido: 'Pérez', curso: 'Matemáticas', promedio: 8.5 },
    { id: 2, nombre: 'María', apellido: 'Gómez', curso: 'Física', promedio: 9.0 },
    { id: 3, nombre: 'Carlos', apellido: 'López', curso: 'Química', promedio: 7.8 },
    { id: 4, nombre: 'Ana', apellido: 'Martínez', curso: 'Biología', promedio: 8.9 },
    { id: 5, nombre: 'Luis', apellido: 'García', curso: 'Historia', promedio: 7.5 },
    { id: 6, nombre: 'Sofía', apellido: 'Rodríguez', curso: 'Geografía', promedio: 8.2 },
    { id: 7, nombre: 'Diego', apellido: 'Hernández', curso: 'Filosofía', promedio: 8.0 },
    { id: 8, nombre: 'Laura', apellido: 'Fernández', curso: 'Literatura', promedio: 9.3 },
    { id: 9, nombre: 'David', apellido: 'Ruiz', curso: 'Inglés', promedio: 8.4 },
    { id: 10, nombre: 'Lucía', apellido: 'Torres', curso: 'Arte', promedio: 9.1 },
    { id: 11, nombre: 'Jorge', apellido: 'Ramírez', curso: 'Educación Física', promedio: 7.7 },
    { id: 12, nombre: 'Andrea', apellido: 'Flores', curso: 'Música', promedio: 8.8 },
    { id: 13, nombre: 'Ricardo', apellido: 'Sánchez', curso: 'Computación', promedio: 9.5 },
    { id: 14, nombre: 'Marta', apellido: 'Ortiz', curso: 'Economía', promedio: 8.7 },
    { id: 15, nombre: 'Manuel', apellido: 'Morales', curso: 'Derecho', promedio: 7.9 },
    { id: 16, nombre: 'Juan', apellido: 'Pérez', curso: 'Matemáticas', promedio: 8.5 },
    { id: 17, nombre: 'María', apellido: 'Gómez', curso: 'Física', promedio: 9.0 },
    { id: 18, nombre: 'Carlos', apellido: 'López', curso: 'Química', promedio: 7.8 },
    { id: 19, nombre: 'Ana', apellido: 'Martínez', curso: 'Biología', promedio: 8.9 },
    { id: 20, nombre: 'Luis', apellido: 'García', curso: 'Historia', promedio: 7.5 },
    { id: 21, nombre: 'Sofía', apellido: 'Rodríguez', curso: 'Geografía', promedio: 8.2 },
    { id: 22, nombre: 'Diego', apellido: 'Hernández', curso: 'Filosofía', promedio: 8.0 },
    { id: 23, nombre: 'Laura', apellido: 'Fernández', curso: 'Literatura', promedio: 9.3 },
    { id: 24, nombre: 'David', apellido: 'Ruiz', curso: 'Inglés', promedio: 8.4 },
    { id: 25, nombre: 'Lucía', apellido: 'Torres', curso: 'Arte', promedio: 9.1 },
    { id: 26, nombre: 'Jorge', apellido: 'Ramírez', curso: 'Educación Física', promedio: 7.7 },
    { id: 27, nombre: 'Andrea', apellido: 'Flores', curso: 'Música', promedio: 8.8 },
    { id: 28, nombre: 'Ricardo', apellido: 'Sánchez', curso: 'Computación', promedio: 9.5 },
    { id: 29, nombre: 'Marta', apellido: 'Ortiz', curso: 'Economía', promedio: 8.7 },
    { id: 30, nombre: 'Manuel', apellido: 'Morales', curso: 'Derecho', promedio: 7.9 },
    { id: 31, nombre: 'Juan', apellido: 'Pérez', curso: 'Matemáticas', promedio: 8.5 },
    { id: 32, nombre: 'María', apellido: 'Gómez', curso: 'Física', promedio: 9.0 },
    { id: 33, nombre: 'Carlos', apellido: 'López', curso: 'Química', promedio: 7.8 },
    { id: 34, nombre: 'Ana', apellido: 'Martínez', curso: 'Biología', promedio: 8.9 },
    { id: 35, nombre: 'Luis', apellido: 'García', curso: 'Historia', promedio: 7.5 },
    { id: 36, nombre: 'Sofía', apellido: 'Rodríguez', curso: 'Geografía', promedio: 8.2 },
    { id: 37, nombre: 'Diego', apellido: 'Hernández', curso: 'Filosofía', promedio: 8.0 },
    { id: 38, nombre: 'Laura', apellido: 'Fernández', curso: 'Literatura', promedio: 9.3 },
    { id: 39, nombre: 'David', apellido: 'Ruiz', curso: 'Inglés', promedio: 8.4 },
    { id: 40, nombre: 'Lucía', apellido: 'Torres', curso: 'Arte', promedio: 9.1 },
    { id: 41, nombre: 'Jorge', apellido: 'Ramírez', curso: 'Educación Física', promedio: 7.7 },
    { id: 42, nombre: 'Andrea', apellido: 'Flores', curso: 'Música', promedio: 8.8 },
    { id: 43, nombre: 'Ricardo', apellido: 'Sánchez', curso: 'Computación', promedio: 9.5 },
    { id: 44, nombre: 'Marta', apellido: 'Ortiz', curso: 'Economía', promedio: 8.7 },
    { id: 45, nombre: 'Manuel', apellido: 'Morales', curso: 'Derecho', promedio: 7.9 }
  ];
  