export const library = [
    {
      id: 1,
      title: "El jardín secreto",
      text: "Mary Lennox era hija de un oficial del ejército inglés y vivía en la India con sus padres. Un día, ambos murieron y Mary quedó sola en el mundo. No le quedaba pariente alguno y todo su patrimonio estaba en la India. Mary era una niña tan delgada y tan fea que no le gustaba a nadie. Mary Lennox era hija de un oficial del ejército inglés y vivía en la India con sus padres. Un día, ambos murieron y Mary quedó sola en el mundo. No le quedaba pariente alguno y todo su patrimonio estaba en la India. Mary era una niña tan delgada y tan fea que no le gustaba a nadie. Mary Lennox era hija de un oficial del ejército inglés y vivía en la India con sus padres. Un día, ambos murieron y Mary quedó sola en el mundo. No le quedaba pariente alguno y todo su patrimonio estaba en la India. Mary era una niña tan delgada y tan fea que no le gustaba a nadie. Mary Lennox era hija de un oficial del ejército inglés y vivía en la India con sus padres. Un día, ambos murieron y Mary quedó sola en el mundo. No le quedaba pariente alguno y todo su patrimonio estaba en la India. Mary era una niña tan delgada y tan fea que no le gustaba a nadie. Mary Lennox era hija de un oficial del ejército inglés y vivía en la India con sus padres. Un día, ambos murieron y Mary quedó sola en el mundo. No le quedaba pariente alguno y todo su patrimonio estaba en la India. Mary era una niña tan delgada y tan fea que no le gustaba a nadie." ,
      author: "Frances Hodgson Burnett"
    },
    {
      id: 2,
      title: "Cien años de soledad",
      text: "Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo.",
      author: "Gabriel García Márquez"
    },
    {
      id: 3,
      title: "Moby Dick",
      text: "Llamadme Ismael. Hace unos años, no importa cuánto hace exactamente, teniendo poco o ningún dinero en mi cartera y nada en particular que me interesara en tierra, pensé en navegar por el mundo y ver las partes acuosas del mundo. el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo.",
      author: "Herman Melville"
    },
    {
      id: 4,
      title: "Orgullo y prejuicio",
      text: "Es una verdad universalmente reconocida que un hombre soltero, poseedor de una gran fortuna, necesita una esposa. el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo.",
      author: "Jane Austen"
    },
    {
      id: 5,
      title: "El conde de Montecristo",
      text: "En el año 1815, el señor Edmundo Dantés, joven capitán de un barco mercante, llegó a Marsella, después de un viaje a bordo del 'Pharaón', procedente de la ciudad de Smirna. Estaba a punto de cumplir veintiséis años; era dueño de un rostro abierto, de ojos claros y mirada penetrante. el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo.",
      author: "Alexandre Dumas"
    },
    {
      id: 6,
      title: "Drácula",
      text: "El 3 de mayo, llegué a Londres a las cinco en punto de la tarde. El sol no se ponía aún, pero la sombra cubría ya toda la ciudad. el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo.",
      author: "Bram Stoker"
    },
    {
      id: 1,
      title: "El jardín secreto",
      text: "Mary Lennox era hija de un oficial del ejército inglés y vivía en la India con sus padres. Un día, ambos murieron y Mary quedó sola en el mundo. No le quedaba pariente alguno y todo su patrimonio estaba en la India. Mary era una niña tan delgada y tan fea que no le gustaba a nadie. Mary Lennox era hija de un oficial del ejército inglés y vivía en la India con sus padres. Un día, ambos murieron y Mary quedó sola en el mundo. No le quedaba pariente alguno y todo su patrimonio estaba en la India. Mary era una niña tan delgada y tan fea que no le gustaba a nadie. Mary Lennox era hija de un oficial del ejército inglés y vivía en la India con sus padres. Un día, ambos murieron y Mary quedó sola en el mundo. No le quedaba pariente alguno y todo su patrimonio estaba en la India. Mary era una niña tan delgada y tan fea que no le gustaba a nadie. Mary Lennox era hija de un oficial del ejército inglés y vivía en la India con sus padres. Un día, ambos murieron y Mary quedó sola en el mundo. No le quedaba pariente alguno y todo su patrimonio estaba en la India. Mary era una niña tan delgada y tan fea que no le gustaba a nadie. Mary Lennox era hija de un oficial del ejército inglés y vivía en la India con sus padres. Un día, ambos murieron y Mary quedó sola en el mundo. No le quedaba pariente alguno y todo su patrimonio estaba en la India. Mary era una niña tan delgada y tan fea que no le gustaba a nadie." ,
      author: "Frances Hodgson Burnett"
    },
    {
      id: 2,
      title: "Cien años de soledad",
      text: "Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo.",
      author: "Gabriel García Márquez"
    },
    {
      id: 3,
      title: "Moby Dick",
      text: "Llamadme Ismael. Hace unos años, no importa cuánto hace exactamente, teniendo poco o ningún dinero en mi cartera y nada en particular que me interesara en tierra, pensé en navegar por el mundo y ver las partes acuosas del mundo. el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo.",
      author: "Herman Melville"
    },
    {
      id: 4,
      title: "Orgullo y prejuicio",
      text: "Es una verdad universalmente reconocida que un hombre soltero, poseedor de una gran fortuna, necesita una esposa. el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo.",
      author: "Jane Austen"
    },
    {
      id: 5,
      title: "El conde de Montecristo",
      text: "En el año 1815, el señor Edmundo Dantés, joven capitán de un barco mercante, llegó a Marsella, después de un viaje a bordo del 'Pharaón', procedente de la ciudad de Smirna. Estaba a punto de cumplir veintiséis años; era dueño de un rostro abierto, de ojos claros y mirada penetrante. el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo.",
      author: "Alexandre Dumas"
    },
    {
      id: 6,
      title: "Drácula",
      text: "El 3 de mayo, llegué a Londres a las cinco en punto de la tarde. El sol no se ponía aún, pero la sombra cubría ya toda la ciudad. el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo.",
      author: "Bram Stoker"
    }
  ];
  